#!/bin/sh
# 30-game.sh — link the Rocket League install (Heroic/Legendary, Epic build)
# into the assets tree as $ASSETS_DIR/game (guest path /game), verify the
# executable, and seed the low-end TASystemSettings.ini in the Wine prefix.
# EAC files are left untouched and never referenced. Idempotent.
set -eu
. "$(dirname "$0")/lib.sh"

game=$(detect_game_dir) || die "Rocket League install not found; set GAME_DIR in laptop/config.env"
log "game dir: $game"
EXE="$game/Binaries/Win64/RocketLeague.exe"
[ -f "$EXE" ] || die "missing $EXE (is this the Epic PC build?)"
if [ "$game" != "$ASSETS_DIR/game" ]; then
  ln -sfn "$game" "$ASSETS_DIR/game"
fi
du -sh "$game" 2>/dev/null | sed 's/^/size: /' >&2
ls "$game/Binaries/Win64" | head -20 >&2
[ -d "$game/Binaries/Win64/EasyAntiCheat" ] && log "note: EasyAntiCheat dir present; it is never loaded (we launch RocketLeague.exe directly)"

# Low-end settings: 720p windowed (Xvfb screen is 1280x720), textures low,
# effects off, 30 fps cap. The game merges these with its defaults.
CFG="$WINEPREFIX_DIR/drive_c/users/user/Documents/My Games/Rocket League/TAGame/Config"
mkdir -p "$CFG"
if [ ! -f "$CFG/TASystemSettings.ini" ] || [ "${FORCE_SETTINGS:-0}" = 1 ]; then
cat > "$CFG/TASystemSettings.ini" <<'EOF'
[SystemSettings]
ResX=1280
ResY=720
Fullscreen=False
Borderless=True
VSync=False
UseVsync=False
bSmoothFrameRate=True
MinSmoothedFrameRate=20
MaxSmoothedFrameRate=30
TextureDetail=TexturesLow
WorldDetail=Low
ParticleDetail=Low
ShadowDetail=Off
Bloom=False
LensFlares=False
LightShafts=False
DynamicShadows=False
MotionBlur=False
DepthOfField=False
AmbientOcclusion=False
WeatherFX=False
HighQualityShaders=False
TransparencyQuality=Low
MaxAnisotropy=1
MaxMultiSamples=1
AllowD3D9MSAA=False
bAllowPostprocessMLAA=False
bAllowPostprocessAA=False
FloatingPointRenderTargets=False
RenderQuality=Performance
EOF
  log "wrote $CFG/TASystemSettings.ini"
else
  log "keeping existing TASystemSettings.ini (FORCE_SETTINGS=1 to overwrite)"
fi

# Launch recipe recorded for the reference runs and the TV init script.
cat > "$ASSETS_DIR/game-launch.env" <<EOF
# generated by 30-game.sh
RL_EXE=Z:\\\\game\\\\Binaries\\\\Win64\\\\RocketLeague.exe
RL_ARGS=-nomovie -nosplash -windowed -ResX=1280 -ResY=720
RL_CWD=/game/Binaries/Win64
EOF
cat "$ASSETS_DIR/game-launch.env" >&2
log "game linked at $ASSETS_DIR/game"
